<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>

    <ApplicationIcon>TypeIt4Me.ico</ApplicationIcon>
    <Version>1.6.0</Version>
    <AssemblyVersion>1.6.0.0</AssemblyVersion>
    <FileVersion>1.6.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="TypeIt4Me.ico" />
    <Compile Remove="IconGen\**" />
    <EmbeddedResource Remove="IconGen\**" />
    <None Remove="IconGen\**" />
  </ItemGroup>

</Project>
